### ISSUE TITLE
branchsim.py outputs and intermediate variables seem strange

### ISSUE THREAD

**Issue by bentoayr** [raphael-group/calder#15]
Hello,

I am trying to make sense of branchsim.py

If I go inside the simulation() routine and I write the cell counts (A) of different clones to a file, and also the clone compositions (B), which can all be found on the N_genotype[] dictionary, I get some results that are incompatible with the results I get from the patient data output files (C) and the edge files output (D).

In particular,

* if I build a tree from (B) that tree does not agree with (D). 
* if I try to infer the clone frequencies based on the mutation frequencies (C) and the tree in (D), I get negative clone frequencies

Can you guide me in making sense of branchsim.py ?

**Comment by mmyers1** [comment]
I used different parameters and a variety of random seeds to generated the simulated instances used in the paper. Many instances of the simulation produced clones that would not persist for the desired sampling duration, so I tested many initializations to obtain simulations that yield the desired properties. 

As such, running simulation() with the default parameters and an arbitrary seed are unlikely to yield the simulations we used in the paper. See this Zenodo repository for the branching sim ground truth and results from the 3 methods: https://zenodo.org/records/13286738
