### ISSUE TITLE
soln_to_timescape issue

### ISSUE THREAD

**Issue by mkinnaman** [raphael-group/calder#2]
Not sure if this is an issue with my data or the script but with two different data sets now I keep getting errors with the soln_to_timescape script.

I keep getting the following error:

Error converting file to Timescape format.
string index out of range

Would appreciate any insights.

Thanks,
Michael

**Comment by bend87** [comment]
Hi Michael,

Could you provide some more information? For starters, the full traceback of the error would be useful, and it would be great if you could describe your data or even replicate this issue on a mocked-up file with dummy data.

-Matt

**Comment by mkinnaman** [comment]
Hey Matt,

It doesnt trigger a full traceback of the error for whatever reason. This is the output:

Error converting file to Timescape format.
string index out of range

Data is from two longitudinally collected rhabdomyosarcoma samples. Attached the .dot and .csv files for your reference.

Thanks,
Michael

[arms.zip](https://github.com/raphael-group/calder/files/4112138/arms.zip)

**Comment by bend87** [comment]
Sorry for the delay in getting to this. It was an issue with the cluster/column name abbreviations I was using (not handling the case with >26 columns), which I just fixed.
